routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('test1',function(){
    return view('test.test1');
});

Route::get('productcategory/create','ProductCategoryController@create');
Route::post('productcategory','ProductCategoryController@store');
Route::get('applicationform/create','ApplicationFormController@view');
Route::post('applicationform','ApplicationFormController@store');
Route::get('test/create','TestController@view');
Route::post('test','TestController@store');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user','UserController');
Route::get('user','UserController@index');
Route::get('user.create','UserController@create');
Route::post('user.store','UserController@store');
Route::get('user.{user}','UserController@show');
Route::get('user.{user}.edit','UserController@edit');
Route::put('user.{user}','UserController@update');
Route::delete('user.{user}','UserController@destroy');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/ProductCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    protected $table = 'Product_categories';
    protected $primaryKey = 'product_category_id';
    public $timestamps = false;
}

app/User.php
<?php
namespace App;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/crud.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class crud extends Model
{
    protected $fillable = [
        'name',
        'airline'
    ];
}

app/Http/Controllers/ApplicationFormController.php
<?php

namespace App\Http\Controllers;

use App\Rules\IdNumberRule;
use App\Rules\RequiredRule;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Http\Controllers\ApplicationFormController;


class ApplicationFormController extends Controller
{
    public function view(){
        return view('productCategory.applicationForm');
    }
    public function store(Request $request){
        $validatedData = $request->validate([
            'username' =>[new RequiredRule],
            'password' => [new RequiredRule],
            'email' => [new RequiredRule],
            'phone' => 'starts_with:0|digits:10',
            'phone' => [new RequiredRule],
            'dob' => [new RequiredRule],
            'idnumber' => [new RequiredRule],
            'idnumber' => [new IdNumberRule]
        ],[
            'username.required'=>'xxxxxx',
            
        ]);

        $name = $request -> post('name');
        $phone = $request -> post('phone');
        $idnumber = $request -> post('idnumber');
        var_dump($name);
        var_dump($phone);
        var_dump($idnumber);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\ProductCategory;

class ProductCategoryController extends Controller
{
    public function create(){
        $categories = DB::table('Product_categories')->get();
        return view('productcategory.create',['categories' => $categories]);
    }

    public function store(Request $request){
        $name = $request -> post('name');
        $display_name = $request -> post('display_name');
        $product_category = new ProductCategory;
        $product_category -> product_category_name = $name;
        $product_category -> product_category_display_name = $display_name;
        $product_category -> save();
        return 'Adding Completed';
    }
}

app/Http/Controllers/TestController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;

class TestController extends Controller
{
    public function view(){
        $product_name = DB::table('Products')->pluck('display_name');
        return view('test.test1',['product_name' => $product_name]);
    }
    public function store(Request $request){

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Crud;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = crud::all();

        return view('contacts.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'airline'=>'required'
        ]);
        $user = new crud([
            'name' => $request->get('name'),
            'airline' => $request->get('airline')
        ]);
        $user->save();
        return redirect('/user')->with('success', 'Contact saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = crud::find($id);
        return view('contacts.edit', compact('user'));  

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'airline'=>'required'
        ]);
        $user = crud::find($id);
        $user->name = $request->get('name');
        $user->airline = $request->get('airline');
        $user->save();
        return redirect('/user')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = crud::find($id);
        $user->delete();
        return redirect('/user')->with('success', 'Delete Completed!');
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lab 6 - CRUD</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/contacts/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a contact</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('user.store') }}">
          @csrf
          <div class="form-group">    
              <label for="name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">
              <label for="airline">Airline:</label>
              <input type="text" class="form-control" name="airline"/>
          </div>                       
          <button type="submit" class="btn btn-primary-outline">Add contact</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/contacts/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a contact</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('user.update', $user->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value={{ $user->name }} />
            </div>

            <div class="form-group">
                <label for="airline">Airline:</label>
                <input type="text" class="form-control" name="airline" value={{ $user->airline }} />
            </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/contacts/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Contacts</h1>    
    <div>
        <a style="margin: 19px;" href="{{ route('user.create')}}" class="btn btn-primary">New contact</a>
        </div>  
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Airline</td>
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$user->id}}</td>
            <td>{{$user->name}}</td>
            <td>{{$user->airline}}</td>
            <td>
                <a href="{{ route('user.edit',$user->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('user.destroy', $user->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
<div class="col-sm-12">

    @if(session()->get('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}  
      </div>
    @endif
  </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/master.blade.php
<html>
    <head>
        <title>Product - @yield('title')</title>
    </head>

    <body>
        <header>
            <h1>this is header</h1>
        </header>

        <nav>
            <h2>This is nav</h2>
        </nav>
        
        <div class="container">
            @section('maincontent')
            <h3>This is main content</h3>
            @show
        </div>

        <aside>
            <h3>This is aside</h3>
        </aside>

        <footer>
            <h2>This is footer</h2>
        </footer>
    </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/productCategory/applicationForm.blade.php
<h2>Register Form</h2>

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

{{Form::open(array('url' => '/applicationform', 'method' => 'post'))}}
    <table>
        <tr>
            <td>Username</td>
            <td>{{Form::text('name')}}</td>
        </tr>

        <tr>
            <td>Password</td>
            <td>{{Form::Password('password')}}</td>
        </tr>

        <tr>
            <td>Email</td>
            <td>{{Form::email('email')}}</td>
        </tr>

        <tr>
            <td>Phone Number</td>
            <td>{{Form::text('phone')}}</td>
        </tr>

        <tr>
            <td>Date of Birth</td>
            <td>{{ Form::date('dob', date('d/m/Y')) }} </td>
        </tr>


        <tr>
            <td>ID Number:</td>
            <td>{{Form::text('idnumber')}}</td>
        </tr>
        <tr>
            <td colspan="2" align="center">{{Form::submit('Submit')}}</td>
        </tr>
    </table>
{{Form::close()}}

resources/views/productCategory/create.blade.php
@extends('layout.master')

@section('title','Create Product Category')
    
@section('maincontent')
{{Form::open(array('url' => '/productcategory', 'method' => 'post'))}}
    <table>
        <tr>
            <td>Name</td>
            <td>{{Form::text('name')}}</td>
        </tr>

        <tr>
            <td>Display Name:</td>
            <td>{{Form::text('display_name')}}</td>
        </tr>

        <tr>
            <td>Drop down:</td>
            <td>
                <select name="product" id="">
                    <?php 
                        foreach ($categories as $category) {
                            echo '<option value='.$category->product_category_id.' >'.$category->product_category_display_name.'</option>';
                        }
                    ?>
                </select>
            </td>
        </tr>
        <tr>
            <td align="center">{{Form::submit('Submit')}}</td>
        </tr>
    </table>
{{Form::close()}}

@endsection